//@ts-nocheck
import type { Bus, Location } from "./types";

export const translations = {
  "en-IN": {
    title: "RSRTC Voice Bus Search",
    placeholder: "Tap the mic and say 'Jaipur to Jodhpur'",
    listening: "Listening...",
    processing: "Processing...",
    error: "Sorry, I didn't catch that. Please try again.",
    noBuses: "No buses found for this route.",
    from: "From",
    to: "To",
    fare: "Fare",
    rupees: "Rupees",
    bookNow: "Book Now",
    route: "Route",
    departure: "Departure",
    arrival: "Arrival",
    duration: "Duration",
    search: "Search",
    foundBuses: "Found {count} {busWord} from {from} to {to}. ",
    firstBusDetails:
      "The first bus is the {name}, a {type} bus, departing from platform number {platform} at {departureTime}. The fare is {fare} Rupees.",
  },
  "hi-IN": {
    title: "आरएसआरटीसी वॉयस बस खोज",
    placeholder: "माइक टैप करें और कहें 'जयपुर से जोधपुर'",
    listening: "सुन रहा हूँ...",
    processing: "प्रोसेस हो रहा है...",
    error: "क्षमा करें, मुझे समझ नहीं आया। कृपया पुनः प्रयास करें।",
    noBuses: "इस रूट के लिए कोई बस नहीं मिली।",
    from: "से",
    to: "तक",
    fare: "किराया",
    rupees: "रुपये",
    bookNow: "अभी बुक करें",
    route: "मार्ग",
    departure: "प्रस्थान",
    arrival: "आगमन",
    duration: "अवधि",
    search: "खोजें",
    foundBuses: "{from} से {to} के लिए {count} {busWord} हैं। ",
    firstBusDetails:
      "पहली बस {name} है, जो एक {type} बस है, प्लेटफॉर्म नंबर {platform} से {departureTime} पर प्रस्थान करेगी। किराया {fare} रुपये है।",
  },
};

export  const locations: Record<string, Location> = {
  jaipur: { en: "Jaipur", hi: "जयपुर" },
  jodhpur: { en: "Jodhpur", hi: "जोधपुर" },
  delhi: { en: "Delhi", hi: "दिल्ली" },
  ajmer: { en: "Ajmer", hi: "अजमेर" },
  beawar: { en: "Beawar", hi: "ब्यावर" },
  pali: { en: "Pali", hi: "पाली" },
  kishangarh: { en: "Kishangarh", hi: "किशनगढ़" },
  dudu: { en: "Dudu", hi: "दूदू" },
  sojat: { en: "Sojat", hi: "सोजत" },
  bagru: { en: "Bagru", hi: "बगरू" },
  behror: { en: "Behror", hi: "बहरोड़" },
  gurugram: { en: "Gurugram", hi: "गुरुग्राम" },
  kotputli: { en: "Kotputli", hi: "कोटपूतली" },
  alwar: { en: "Alwar", hi: "अलवर" },
  udaipur: { en: "Udaipur", hi: "उदयपुर" },
  bhilwara: { en: "Bhilwara", hi: "भीलवाड़ा" },
  chittorgarh: { en: "Chittorgarh", hi: "चित्तौड़गढ़" },
  bikaner: { en: "Bikaner", hi: "बीकानेर" },
  kota: { en: "Kota", hi: "कोटा" },
  bharatpur: { en: "Bharatpur", hi: "भरतपुर" },
  agra: { en: "Agra", hi: "आगरा" },
  mathura: { en: "Mathura", hi: "मथुरा" },
  lucknow: { en: "Lucknow", hi: "लखनऊ" },
  sikar: { en: "Sikar", hi: "सीकर" },
  churu: { en: "Churu", hi: "चूरू" },
  tonk: { en: "Tonk", hi: "टोंक" },
  sawaimadhopur: { en: "Sawai Madhopur", hi: "सवाई माधोपुर" },
  bundi: { en: "Bundi", hi: "बूंदी" },
  nathdwara: { en: "Nathdwara", hi: "नाथद्वारा" },
  neemrana: { en: "Neemrana", hi: "नीमराना" },
  shahpura: { en: "Shahpura", hi: "शाहपुरा" },
  ratangarh: { en: "Ratangarh", hi: "रतनगढ़" },
  sirohi: { en: "Sirohi", hi: "सिरोही" },
  mountabu: { en: "Mount Abu", hi: "माउंट आबू" },
};



export const DUMMY_BUSES: Bus[] = [
  // Jaipur to Jodhpur routes
  {
    id: "B101",
    name: "Marudhar Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.jodhpur,
    departureTime: "06:00",
    arrivalTime: "12:00",
    duration: "6h 0m",
    fare: 450,
    platform: 5,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.beawar,
      locations.pali,
      locations.jodhpur,
    ],
  },
  {
    id: "B102",
    name: "Royal Volvo",
    type: "Volvo",
    from: locations.jaipur,
    to: locations.jodhpur,
    departureTime: "09:30",
    arrivalTime: "15:00",
    duration: "5h 30m",
    fare: 700,
    platform: 2,
    route: [
      locations.jaipur,
      locations.kishangarh,
      locations.ajmer,
      locations.pali,
      locations.jodhpur,
    ],
  },
  {
    id: "B103",
    name: "Express Bus",
    type: "Express",
    from: locations.jaipur,
    to: locations.jodhpur,
    departureTime: "22:00",
    arrivalTime: "04:00",
    duration: "6h 0m",
    fare: 600,
    platform: 5,
    route: [
      locations.jaipur,
      locations.dudu,
      locations.ajmer,
      locations.sojat,
      locations.jodhpur,
    ],
  },
  {
    id: "B104",
    name: "Pink City Deluxe",
    type: "Deluxe",
    from: locations.jaipur,
    to: locations.jodhpur,
    departureTime: "14:30",
    arrivalTime: "20:30",
    duration: "6h 0m",
    fare: 500,
    platform: 3,
    route: [
      locations.jaipur,
      locations.bagru,
      locations.ajmer,
      locations.pali,
      locations.jodhpur,
    ],
  },
  {
    id: "B105",
    name: "Volvo AC",
    type: "Volvo",
    from: locations.jaipur,
    to: locations.jodhpur,
    departureTime: "16:45",
    arrivalTime: "22:15",
    duration: "5h 30m",
    fare: 465,
    platform: 6,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.beawar,
      locations.pali,
      locations.jodhpur,
    ],
  },

  // Jaipur to Delhi routes
  {
    id: "B201",
    name: "AC Sleeper",
    type: "Sleeper",
    from: locations.jaipur,
    to: locations.delhi,
    departureTime: "07:00",
    arrivalTime: "12:30",
    duration: "5h 30m",
    fare: 800,
    platform: 1,
    route: [
      locations.jaipur,
      locations.behror,
      locations.gurugram,
      locations.delhi,
    ],
  },
  {
    id: "B202",
    name: "Super Deluxe",
    type: "Deluxe",
    from: locations.jaipur,
    to: locations.delhi,
    departureTime: "23:00",
    arrivalTime: "05:00",
    duration: "6h 0m",
    fare: 750,
    platform: 1,
    route: [
      locations.jaipur,
      locations.kotputli,
      locations.gurugram,
      locations.delhi,
    ],
  },
  {
    id: "B203",
    name: "Pink Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.delhi,
    departureTime: "08:30",
    arrivalTime: "14:00",
    duration: "5h 30m",
    fare: 550,
    platform: 2,
    route: [
      locations.jaipur,
      locations.shahpura,
      locations.kotputli,
      locations.gurugram,
      locations.delhi,
    ],
  },
  {
    id: "B204",
    name: "Fast Passenger",
    type: "Express",
    from: locations.jaipur,
    to: locations.delhi,
    departureTime: "15:30",
    arrivalTime: "21:00",
    duration: "5h 30m",
    fare: 620,
    platform: 3,
    route: [
      locations.jaipur,
      locations.neemrana,
      locations.gurugram,
      locations.delhi,
    ],
  },

  // Jodhpur to Jaipur routes
  {
    id: "B301",
    name: "AC Sleeper Coach",
    type: "Sleeper",
    from: locations.jodhpur,
    to: locations.jaipur,
    departureTime: "08:00",
    arrivalTime: "14:00",
    duration: "6h 0m",
    fare: 450,
    platform: 4,
    route: [
      locations.jodhpur,
      locations.pali,
      locations.beawar,
      locations.ajmer,
      locations.jaipur,
    ],
  },
  {
    id: "B302",
    name: "Blue City Volvo",
    type: "Volvo",
    from: locations.jodhpur,
    to: locations.jaipur,
    departureTime: "15:00",
    arrivalTime: "20:30",
    duration: "5h 30m",
    fare: 700,
    platform: 1,
    route: [
      locations.jodhpur,
      locations.pali,
      locations.ajmer,
      locations.kishangarh,
      locations.jaipur,
    ],
  },
  {
    id: "B303",
    name: "Marwar Express",
    type: "Express",
    from: locations.jodhpur,
    to: locations.jaipur,
    departureTime: "11:30",
    arrivalTime: "17:30",
    duration: "6h 0m",
    fare: 465,
    platform: 3,
    route: [
      locations.jodhpur,
      locations.sojat,
      locations.ajmer,
      locations.jaipur,
    ],
  },

  // Delhi to Jaipur routes
  {
    id: "B401",
    name: "Express Bus",
    type: "Express",
    from: locations.delhi,
    to: locations.jaipur,
    departureTime: "09:00",
    arrivalTime: "15:00",
    duration: "6h 0m",
    fare: 780,
    platform: 8,
    route: [
      locations.delhi,
      locations.gurugram,
      locations.behror,
      locations.jaipur,
    ],
  },
  {
    id: "B402",
    name: "NCR Volvo",
    type: "Volvo",
    from: locations.delhi,
    to: locations.jaipur,
    departureTime: "10:30",
    arrivalTime: "16:00",
    duration: "5h 30m",
    fare: 850,
    platform: 6,
    route: [
      locations.delhi,
      locations.gurugram,
      locations.neemrana,
      locations.jaipur,
    ],
  },
  {
    id: "B403",
    name: "Super Deluxe",
    type: "Deluxe",
    from: locations.delhi,
    to: locations.jaipur,
    departureTime: "14:00",
    arrivalTime: "19:30",
    duration: "5h 30m",
    fare: 580,
    platform: 7,
    route: [
      locations.delhi,
      locations.gurugram,
      locations.kotputli,
      locations.jaipur,
    ],
  },

  // Jaipur to Udaipur routes
  {
    id: "B501",
    name: "Lake City Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.udaipur,
    departureTime: "06:30",
    arrivalTime: "12:30",
    duration: "6h 0m",
    fare: 480,
    platform: 7,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.beawar,
      locations.nathdwara,
      locations.udaipur,
    ],
  },
  {
    id: "B502",
    name: "Mewar Deluxe",
    type: "Deluxe",
    from: locations.jaipur,
    to: locations.udaipur,
    departureTime: "15:00",
    arrivalTime: "21:30",
    duration: "6h 30m",
    fare: 550,
    platform: 4,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.chittorgarh,
      locations.udaipur,
    ],
  },
  {
    id: "B503",
    name: "Volvo AC Coach",
    type: "Volvo",
    from: locations.jaipur,
    to: locations.udaipur,
    departureTime: "20:30",
    arrivalTime: "03:00",
    duration: "6h 30m",
    fare: 780,
    platform: 9,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.nathdwara,
      locations.udaipur,
    ],
  },

  // Udaipur to Jaipur routes
  {
    id: "B601",
    name: "Fast Passenger",
    type: "Express",
    from: locations.udaipur,
    to: locations.jaipur,
    departureTime: "07:30",
    arrivalTime: "13:30",
    duration: "6h 0m",
    fare: 480,
    platform: 3,
    route: [
      locations.udaipur,
      locations.nathdwara,
      locations.beawar,
      locations.ajmer,
      locations.jaipur,
    ],
  },
  {
    id: "B602",
    name: "Aravalli Express",
    type: "Deluxe",
    from: locations.udaipur,
    to: locations.jaipur,
    departureTime: "16:00",
    arrivalTime: "22:30",
    duration: "6h 30m",
    fare: 550,
    platform: 2,
    route: [
      locations.udaipur,
      locations.chittorgarh,
      locations.ajmer,
      locations.jaipur,
    ],
  },

  // Jaipur to Bikaner routes
  {
    id: "B701",
    name: "Fast Passenger",
    type: "Express",
    from: locations.jaipur,
    to: locations.bikaner,
    departureTime: "07:45",
    arrivalTime: "13:45",
    duration: "6h 0m",
    fare: 420,
    platform: 9,
    route: [
      locations.jaipur,
      locations.sikar,
      locations.churu,
      locations.bikaner,
    ],
  },
  {
    id: "B702",
    name: "Camel City Volvo",
    type: "Volvo",
    from: locations.jaipur,
    to: locations.bikaner,
    departureTime: "16:30",
    arrivalTime: "22:00",
    duration: "5h 30m",
    fare: 680,
    platform: 11,
    route: [
      locations.jaipur,
      locations.sikar,
      locations.ratangarh,
      locations.bikaner,
    ],
  },
  {
    id: "B703",
    name: "Volvo AC Coach",
    type: "Volvo",
    from: locations.jaipur,
    to: locations.bikaner,
    departureTime: "12:15",
    arrivalTime: "18:15",
    duration: "6h 0m",
    fare: 480,
    platform: 8,
    route: [
      locations.jaipur,
      locations.sikar,
      locations.churu,
      locations.bikaner,
    ],
  },

  // Bikaner to Jaipur routes
  {
    id: "B801",
    name: "Express Bus",
    type: "Express",
    from: locations.bikaner,
    to: locations.jaipur,
    departureTime: "08:30",
    arrivalTime: "14:30",
    duration: "6h 0m",
    fare: 420,
    platform: 2,
    route: [
      locations.bikaner,
      locations.churu,
      locations.sikar,
      locations.jaipur,
    ],
  },
  {
    id: "B802",
    name: "Junagarh Deluxe",
    type: "Deluxe",
    from: locations.bikaner,
    to: locations.jaipur,
    departureTime: "18:00",
    arrivalTime: "00:00",
    duration: "6h 0m",
    fare: 480,
    platform: 4,
    route: [
      locations.bikaner,
      locations.ratangarh,
      locations.sikar,
      locations.jaipur,
    ],
  },

  // Jaipur to Kota routes
  {
    id: "B901",
    name: "Hadoti Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.kota,
    departureTime: "08:00",
    arrivalTime: "13:00",
    duration: "5h 0m",
    fare: 380,
    platform: 12,
    route: [
      locations.jaipur,
      locations.tonk,
      locations.sawaimadhopur,
      locations.kota,
    ],
  },
  {
    id: "B902",
    name: "Education City Deluxe",
    type: "Deluxe",
    from: locations.jaipur,
    to: locations.kota,
    departureTime: "19:30",
    arrivalTime: "00:30",
    duration: "5h 0m",
    fare: 450,
    platform: 10,
    route: [
      locations.jaipur,
      locations.tonk,
      locations.bundi,
      locations.kota,
    ],
  },
  {
    id: "B903",
    name: "Express Bus",
    type: "Express",
    from: locations.jaipur,
    to: locations.kota,
    departureTime: "14:30",
    arrivalTime: "19:30",
    duration: "5h 0m",
    fare: 650,
    platform: 5,
    route: [
      locations.jaipur,
      locations.sawaimadhopur,
      locations.kota,
    ],
  },

  // Kota to Jaipur routes
  {
    id: "B1001",
    name: "Express Bus",
    type: "Express",
    from: locations.kota,
    to: locations.jaipur,
    departureTime: "09:00",
    arrivalTime: "14:00",
    duration: "5h 0m",
    fare: 380,
    platform: 5,
    route: [
      locations.kota,
      locations.sawaimadhopur,
      locations.tonk,
      locations.jaipur,
    ],
  },
  {
    id: "B1002",
    name: "Chambal Express",
    type: "Deluxe",
    from: locations.kota,
    to: locations.jaipur,
    departureTime: "17:45",
    arrivalTime: "22:45",
    duration: "5h 0m",
    fare: 450,
    platform: 3,
    route: [
      locations.kota,
      locations.bundi,
      locations.tonk,
      locations.jaipur,
    ],
  },

  // Jaipur to Ajmer routes
  {
    id: "B1101",
    name: "Pushkar Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.ajmer,
    departureTime: "06:15",
    arrivalTime: "08:45",
    duration: "2h 30m",
    fare: 180,
    platform: 13,
    route: [
      locations.jaipur,
      locations.dudu,
      locations.ajmer,
    ],
  },
  {
    id: "B1102",
    name: "Dargah Express",
    type: "Express",
    from: locations.jaipur,
    to: locations.ajmer,
    departureTime: "10:30",
    arrivalTime: "12:30",
    duration: "2h 0m",
    fare: 190,
    platform: 5,
    route: [
      locations.jaipur,
      locations.kishangarh,
      locations.ajmer,
    ],
  },
  {
    id: "B1103",
    name: "Express Bus",
    type: "Express",
    from: locations.jaipur,
    to: locations.ajmer,
    departureTime: "18:00",
    arrivalTime: "20:30",
    duration: "2h 30m",
    fare: 220,
    platform: 7,
    route: [
      locations.jaipur,
      locations.dudu,
      locations.ajmer,
    ],
  },

  // Ajmer to Jaipur routes
  {
    id: "B1201",
    name: "Sufi Express",
    type: "Express",
    from: locations.ajmer,
    to: locations.jaipur,
    departureTime: "16:00",
    arrivalTime: "18:00",
    duration: "2h 0m",
    fare: 180,
    platform: 1,
    route: [
      locations.ajmer,
      locations.kishangarh,
      locations.jaipur,
    ],
  },
  {
    id: "B1202",
    name: "Khwaja Express",
    type: "Deluxe",
    from: locations.ajmer,
    to: locations.jaipur,
    departureTime: "20:30",
    arrivalTime: "23:00",
    duration: "2h 30m",
    fare: 220,
    platform: 2,
    route: [
      locations.ajmer,
      locations.dudu,
      locations.jaipur,
    ],
  },

  // Mount Abu routes
  {
    id: "B1301",
    name: "Express Bus",
    type: "Express",
    from: locations.jaipur,
    to: locations.mountabu,
    departureTime: "20:00",
    arrivalTime: "06:00",
    duration: "10h 0m",
    fare: 680,
    platform: 14,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.sirohi,
      locations.mountabu,
    ],
  },
  {
    id: "B1302",
    name: "Green Line",
    type: "Sleeper",
    from: locations.jaipur,
    to: locations.mountabu,
    departureTime: "21:30",
    arrivalTime: "07:30",
    duration: "10h 0m",
    fare: 780,
    platform: 11,
    route: [
      locations.jaipur,
      locations.ajmer,
      locations.udaipur,
      locations.sirohi,
      locations.mountabu,
    ],
  },

  // Alwar routes
  {
    id: "B1401",
    name: "Express Bus",
    type: "Express",
    from: locations.jaipur,
    to: locations.alwar,
    departureTime: "07:30",
    arrivalTime: "10:30",
    duration: "3h 0m",
    fare: 220,
    platform: 15,
    route: [
      locations.jaipur,
      locations.shahpura,
      locations.alwar,
    ],
  },
  {
    id: "B1402",
    name: "Sariska Deluxe",
    type: "Deluxe",
    from: locations.alwar,
    to: locations.jaipur,
    departureTime: "15:00",
    arrivalTime: "18:00",
    duration: "3h 0m",
    fare: 250,
    platform: 2,
    route: [
      locations.alwar,
      locations.shahpura,
      locations.jaipur,
    ],
  },
];

